# .travis.yml for ctypeslib2

language: python

python:
  - "2.7"
# python-clang is Python2 only
#  - "3.4"


install:
# travis-ci use Ubuntu 12.04.5 LTS (Precise Pangolin) 64bit
  - sudo apt-add-repository "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main" --yes
  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main"  --yes
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update
# arrrh... http://docs.travis-ci.com/user/languages/python/.
# system python package will not be used. Can't use python-clang, have to use pip.
  - sudo apt-get install libclang1-4.0 --yes --force-yes
#permission denied  - sudo echo `echo "/usr/lib/llvm-4.0/lib/" >> /etc/ld.so.conf.d/llvm-dev.conf`
  - sudo ln -v -s /usr/lib/x86_64-linux-gnu/libclang-4.0.so.1 /usr/lib/x86_64-linux-gnu/libclang.so
  - sudo ldconfig
# tests dependencies
  - pip install coveralls

script:
# we need clang2py in the path. also installs python clang
  - python setup.py develop
# run tests
  - python setup.py test

after_success:
  - coverage run --source=ctypeslib setup.py test
  - coveralls

# disable email notifications
notifications:
  email:
    on_success: never
    on_failure: never
